### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kincsescsaba** [StanGirard/SEOToolkit#36]
Hi,
I get Internal Server Errors whenever I try to generate a report (Lighthouse or other) from a site, which is hosted on localhost.
What can be the reason?

**Comment by StanGirard** [comment]
Have you tried with the https:// before the website name ?

**Comment by kincsescsaba** [comment]
HTTPS is not set for the site hosted on localhost. Retried though, same error

**Comment by StanGirard** [comment]
Ah sorry :) Lighthouse doesn't work with localhost I think. Never tested thought locally.

I'm using this package -> https://www.npmjs.com/package/lighthouse#using-the-node-cli

Maybe try it and let me know if it works with a local website.
