### ISSUE TITLE
Node Version Update  / Server Dockerfile

### ISSUE THREAD

**Issue by RR-Helpdesk** [StanGirard/SEOToolkit#43]
Build stops at Lighthouse Step 15 with Node v12. I updated the Dockerfile to pull Node v14 and was able to proceed, but may need to update your dependencies here. 

Step 15/34 : RUN yarn global add lighthouse
 ---> Running in 8b4b96307626
yarn global v1.22.17
[1/4] Resolving packages...
warning lighthouse > intl-messageformat > intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
warning lighthouse > raven > uuid@3.3.2: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "lighthouse@9.2.0" with binaries:
      - lighthouse
      - chrome-debug
      - smokehouse
Done in 7.71s.
Removing intermediate container 8b4b96307626

**Comment by StanGirard** [comment]
Hello @RevRebel , thanks for the update :) 
Could you do a PR with your update ?

**Comment by taghead** [comment]
Hello I was having the same issue so I just bumped the node version in the dockerfile. Figured I'd make a pull request.

https://github.com/StanGirard/seo-audits-toolkit/pull/53
