### ISSUE TITLE
Cannot login to remote OSAT hosted on dev server

### ISSUE THREAD

**Issue by mm86133** [StanGirard/SEOToolkit#57]
Following step by step tutorial I will always get the network error. Logs are empty (there is no error logged on dashboard/server).

I have tried adding new user but it is the same issue.

I have tried to add:

`# General
NAMESPACE=sas
SERVER_PORT=5301
FRONT_PORT=5302
JSON_URL=""
SERVER_URL=http://IP:5301
FRONTEND_URL=http://IP:5302
SCAN_DEFAULT_MAX_REQUESTS=0
YAKE_SERVER_URL=http://yake:5000/yake/
# PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true`

With the IP of the server, but it doesn't work either.

How can I setup it to access it remotely ???

**Comment by StanGirard** [comment]
There is something to change in the Front :) 
It look for localhost.
