### ISSUE TITLE
api/extract/links relative link doesn't get resolved correctly

### ISSUE THREAD

**Issue by SimonSchubert** [StanGirard/SEOToolkit#8]
I'm on: 4082a37
I executed the following end point: http://localhost:5000/api/extract/links?url=https://schubert-simon.de

I expected that child 9 and 10 of the `200` array should be:
"https://schubert-simon.de#places"
"https://schubert-simon.de#photos"
But had been:
"http://whatch.online#places"
"http://whatch.online#photos"

And `#projects` in `500` should be "https://schubert-simon.de#projects".

HTML example:
```
<a href="#photos" id="photos">
  <h2>PHOTOS</h2>
</a>
```

Maybe it has something todo with the caching but I did a "fresh" install of the repo. Can you reproduce it? Thanks a lot.

**Comment by StanGirard** [comment]
@SimonSchubert I just reproduced it and found the issue. I was replacing the input URL of the function with the new URL found.
I just fixed it. 

Please let me know if it is ok on your side but it looks good on mine.

Waiting on you to close the issue.
BTW, very nice website!

**Comment by StanGirard** [comment]
Bug fix not working. I'll look into it in a couple of hours

**Comment by SimonSchubert** [comment]
Thanks a lot for the quick fix! API call works like a charm. Everything as expected.

Just one little thing: on the dashboard(http://localhost:5000/extract/links/) the link gets displayed like this "https://schubert-simon.de/ #projects" with a space in between.

Thanks a lot for the compliment. You see, neither you or me is a "good front-end developer" but somehow we manage to deliver something pleasing to look at.

**Comment by StanGirard** [comment]
@SimonSchubert  Thanks. Front-end is overrated :D 

I'm not having this issue that you mentioned with the space. 

I've updated the template that displays the links in the last commits so that you get all the status codes and not only 200. Please see if the new update changes anything.

**Comment by SimonSchubert** [comment]
I fetched the latest commit and now I also don't see the space any more. Thanks again, issue can be closed :)
